/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id              INT  GENERATED ALWAYS AS IDENTITY,
    name            VARCHAR(100),
    date_of_birth   DATE,
    escape_attempts INT,
    neutered        BIT,
    weight_kg       FLOAT
);

ALTER TABLE animals ADD species VARCHAR(100);

CREATE TABLE OWNERS(
ID        INT   GENERATED ALWAYS AS IDENTITY, 
FULL_NAME VARCHAR(100) NOT NULL,
AGE       INT   NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE SPECIES(
ID   INT   GENERATED ALWAYS AS IDENTITY, 
NAME VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)         
);

ALTER TABLE animals 
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
ADD FOREIGN KEY (species_id)
REFERENCES species(id)
ON DELETE CASCADE;

ALTER TABLE animals
ADD COLUMN owner_id INT;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id)
REFERENCES owners(id)
ON DELETE CASCADE;

CREATE TABLE VETS (
ID      INT    GENERATED ALWAYS AS IDENTITY,
NAME    VARCHAR(100) NOT NULL,
AGE     INT         NOT NULL,
DATE_OF_GRADUATION  DATE NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE SPECIALIZATION(
ID    INT  GENERATED ALWAYS AS IDENTITY,
SPECIES_ID INT NOT NULL,
VET_ID     INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES(ID),
FOREIGN KEY (VET_ID) REFERENCES VETS(ID)
);

CREATE TABLE VISITS (
    ID INT GENERATED ALWAYS AS IDENTITY,
    ANIMAL_ID INT NOT NULL,
    VET_ID INT NOT NULL,
    DATE_OF_VISIT DATE NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMALS(ID),
    FOREIGN KEY (VET_ID) REFERENCES VETS(ID)
);